server:
  port: 8082
spring:
  application:
    name: auth-service
  cloud:
    discovery:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, info, health, metrics, loggers, httptrace
  zipkin:
    tracing:
      endpoint: none
      enabled: false