server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  webflux:
    static-path-pattern: /**

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api-app/v1.0.0/user-service/**
          filters:
            - StripPrefix=3

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api-app/v1.0.0/product-service/**
          filters:
            - StripPrefix=3

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api-app/v1.0.0/auth-service/**
          filters:
            - StripPrefix=3

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:

      - name: user-service
        url: /api-app/v1.0.0/user-service/v3/api-docs

      - name: product-service
        url: /api-app/v1.0.0/product-service/v3/api-docs

      - name: auth-service
        url: /api-app/v1.0.0/auth-service/v3/api-docs

    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, info, health, metrics, loggers, httptrace
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: none
      enabled: false
