server:
  port: 8083
spring:
  application:
    name: product-service
  cloud:
    discovery:
      enabled: true
  oauth2:
    resourceserver:
      jwt:
        secret-key: changeMeChangeMeChangeMeChangeMe123
#        jwk-set-uri: http://auth-service:8081/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
